# Generated by Django 5.2.16 on 2026-07-17 00:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, unique=True, verbose_name='alias')),
                ('avatar_url', models.URLField(blank=True, verbose_name='URL del avatar')),
                ('biografia', models.TextField(blank=True, verbose_name='biografía')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=12, verbose_name='estado')),
                ('nivel_acceso', models.CharField(blank=True, choices=[('MODERADOR', 'Moderador'), ('SUPERADMIN', 'Superadministrador')], help_text='Solo aplica a los administradores.', max_length=12, verbose_name='nivel de acceso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_interes', models.PositiveSmallIntegerField(default=3, help_text='RN-04: pondera el algoritmo de recomendación (1 a 5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='nivel de interés')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='catalog.genero', verbose_name='género')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='accounts.perfil', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'preferencia',
                'verbose_name_plural': 'preferencias',
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='generos',
            field=models.ManyToManyField(related_name='perfiles', through='accounts.Preferencia', to='catalog.genero', verbose_name='géneros preferidos'),
        ),
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('BLOQUEADA', 'Bloqueada')], default='PENDIENTE', max_length=10, verbose_name='estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='fecha de solicitud')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de aceptación')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='destinatario')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'amistad',
                'verbose_name_plural': 'amistades',
                'constraints': [models.UniqueConstraint(fields=('solicitante', 'destinatario'), name='amistad_unica_entre_usuarios'), models.CheckConstraint(condition=models.Q(('solicitante', models.F('destinatario')), _negated=True), name='amistad_sin_auto_referencia')],
            },
        ),
        migrations.AddConstraint(
            model_name='preferencia',
            constraint=models.UniqueConstraint(fields=('perfil', 'genero'), name='preferencia_unica_por_perfil_y_genero'),
        ),
    ]
