# Generated by Django 5.2.16 on 2026-07-17 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='puntuación')),
                ('origen', models.CharField(choices=[('PREFERENCIAS', 'Tus géneros preferidos'), ('AMIGOS', 'Valoraciones de tus amigos'), ('HISTORIAL', 'Tu historial de valoraciones'), ('POPULARIDAD', 'Popular en MovieMatch')], default='POPULARIDAD', max_length=14, verbose_name='origen')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='motivo')),
                ('fecha_generada', models.DateTimeField(auto_now_add=True, verbose_name='fecha de generación')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='catalog.contenidoaudiovisual', verbose_name='contenido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'recomendación',
                'verbose_name_plural': 'recomendaciones',
                'ordering': ['-score'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'contenido'), name='recomendacion_unica_por_usuario_y_contenido')],
            },
        ),
    ]
