# Generated by Django 5.2.16 on 2026-07-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaDeUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('USUARIOS_ACTIVOS', 'Usuarios activos'), ('RECOMENDACIONES', 'Recomendaciones generadas'), ('VALORACIONES', 'Valoraciones registradas'), ('TIEMPO_RESPUESTA', 'Tiempo de respuesta (s)'), ('TASA_ERROR', 'Tasa de error (%)')], max_length=20, verbose_name='tipo')),
                ('valor', models.FloatField(verbose_name='valor')),
                ('fecha_corte', models.DateField(verbose_name='fecha de corte')),
            ],
            options={
                'verbose_name': 'métrica de uso',
                'verbose_name_plural': 'métricas de uso',
                'ordering': ['-fecha_corte', 'tipo'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'fecha_corte'), name='metrica_unica_por_tipo_y_fecha')],
            },
        ),
    ]
