# Generated by Django 5.2.16 on 2026-07-17 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoAudiovisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('sinopsis', models.TextField(blank=True, verbose_name='sinopsis')),
                ('anio_estreno', models.PositiveIntegerField(verbose_name='año de estreno')),
                ('poster_url', models.URLField(blank=True, verbose_name='URL del póster')),
                ('clasificacion', models.CharField(blank=True, max_length=10, verbose_name='clasificación')),
                ('estado', models.CharField(choices=[('PUBLICADO', 'Publicado'), ('RETIRADO', 'Retirado')], default='PUBLICADO', max_length=12, verbose_name='estado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'contenido audiovisual',
                'verbose_name_plural': 'contenidos audiovisuales',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'género',
                'verbose_name_plural': 'géneros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('contenidoaudiovisual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.contenidoaudiovisual')),
                ('duracion_min', models.PositiveIntegerField(verbose_name='duración en minutos')),
            ],
            options={
                'verbose_name': 'película',
                'verbose_name_plural': 'películas',
            },
            bases=('catalog.contenidoaudiovisual',),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('contenidoaudiovisual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.contenidoaudiovisual')),
                ('num_temporadas', models.PositiveIntegerField(default=1, verbose_name='número de temporadas')),
                ('num_episodios', models.PositiveIntegerField(default=1, verbose_name='número de episodios')),
                ('en_emision', models.BooleanField(default=False, verbose_name='en emisión')),
            ],
            options={
                'verbose_name': 'serie',
                'verbose_name_plural': 'series',
            },
            bases=('catalog.contenidoaudiovisual',),
        ),
        migrations.AddField(
            model_name='contenidoaudiovisual',
            name='generos',
            field=models.ManyToManyField(related_name='contenidos', to='catalog.genero', verbose_name='géneros'),
        ),
    ]
