# Generated by Django 5.2.16 on 2026-07-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoaudiovisual',
            name='backdrop_url',
            field=models.URLField(blank=True, verbose_name='URL del fondo panorámico'),
        ),
    ]
